# Site settings
title: UPennalizers Website
description: ""
baseurl: "/~robocup"
# url: ""

# Build settings
markdown: kramdown
permalink: pretty

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
